# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_control_panel/app/frontend/gui/AddNewCameraDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCamera(object):
    def setupUi(self, AddCamera):
        AddCamera.setObjectName("AddCamera")
        AddCamera.setWindowModality(QtCore.Qt.ApplicationModal)
        AddCamera.resize(332, 359)
        AddCamera.setMinimumSize(QtCore.QSize(332, 359))
        AddCamera.setMaximumSize(QtCore.QSize(374, 391))
        AddCamera.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(AddCamera)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(AddCamera)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(AddCamera)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nameInput = QtWidgets.QLineEdit(AddCamera)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nameInput)
        self.label = QtWidgets.QLabel(AddCamera)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.protocalInput = QtWidgets.QLineEdit(AddCamera)
        self.protocalInput.setPlaceholderText("")
        self.protocalInput.setObjectName("protocalInput")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.protocalInput)
        self.label_4 = QtWidgets.QLabel(AddCamera)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ipAddressInput = QtWidgets.QLineEdit(AddCamera)
        self.ipAddressInput.setObjectName("ipAddressInput")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ipAddressInput)
        self.label_3 = QtWidgets.QLabel(AddCamera)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pathInput = QtWidgets.QLineEdit(AddCamera)
        self.pathInput.setObjectName("pathInput")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pathInput)
        self.progressBar = QtWidgets.QProgressBar(AddCamera)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(AddCamera)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.addCamera = QtWidgets.QPushButton(AddCamera)
        self.addCamera.setObjectName("addCamera")
        self.horizontalLayout.addWidget(self.addCamera)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.retranslateUi(AddCamera)
        QtCore.QMetaObject.connectSlotsByName(AddCamera)

    def retranslateUi(self, AddCamera):
        _translate = QtCore.QCoreApplication.translate
        AddCamera.setWindowTitle(_translate("AddCamera", "Add New Camera"))
        self.label_5.setText(_translate("AddCamera", "Add New Camera"))
        self.label_2.setText(_translate("AddCamera", "Camera Name"))
        self.label.setText(_translate("AddCamera", "Protocal"))
        self.protocalInput.setText(_translate("AddCamera", "rtsp"))
        self.label_4.setText(_translate("AddCamera", "IP Address"))
        self.label_3.setText(_translate("AddCamera", "Path"))
        self.cancel.setText(_translate("AddCamera", "Cancel"))
        self.addCamera.setText(_translate("AddCamera", "Add"))
