# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_control_panel/app/frontend/gui/AddNewLocationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddLocation(object):
    def setupUi(self, AddLocation):
        AddLocation.setObjectName("AddLocation")
        AddLocation.setWindowModality(QtCore.Qt.ApplicationModal)
        AddLocation.resize(328, 179)
        AddLocation.setMinimumSize(QtCore.QSize(328, 179))
        AddLocation.setMaximumSize(QtCore.QSize(328, 179))
        AddLocation.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(AddLocation)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(AddLocation)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.label = QtWidgets.QLabel(AddLocation)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.locationInput = QtWidgets.QLineEdit(AddLocation)
        self.locationInput.setObjectName("locationInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.locationInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(AddLocation)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.addLocation = QtWidgets.QPushButton(AddLocation)
        self.addLocation.setObjectName("addLocation")
        self.horizontalLayout.addWidget(self.addLocation)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(AddLocation)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.progressBar)

        self.retranslateUi(AddLocation)
        QtCore.QMetaObject.connectSlotsByName(AddLocation)

    def retranslateUi(self, AddLocation):
        _translate = QtCore.QCoreApplication.translate
        AddLocation.setWindowTitle(_translate("AddLocation", "Add Location"))
        self.label_2.setText(_translate("AddLocation", "Add New Location"))
        self.label.setText(_translate("AddLocation", "Name"))
        self.cancel.setText(_translate("AddLocation", "Cancel"))
        self.addLocation.setText(_translate("AddLocation", "Add"))
