# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/HCPMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 537)
        MainWindow.setMinimumSize(QtCore.QSize(662, 524))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(576, 310))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.rooms = QtWidgets.QTreeView(self.splitter)
        self.rooms.setMinimumSize(QtCore.QSize(200, 0))
        self.rooms.setMaximumSize(QtCore.QSize(266, 16777215))
        self.rooms.setStyleSheet("")
        self.rooms.setObjectName("rooms")
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(360, 310))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.cameras = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.cameras.setContentsMargins(0, 0, 0, 0)
        self.cameras.setObjectName("cameras")
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 1)
        self.WatchdogLogo = QtWidgets.QLabel(self.centralwidget)
        self.WatchdogLogo.setMinimumSize(QtCore.QSize(638, 62))
        self.WatchdogLogo.setMaximumSize(QtCore.QSize(16777215, 62))
        self.WatchdogLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.WatchdogLogo.setObjectName("WatchdogLogo")
        self.gridLayout_2.addWidget(self.WatchdogLogo, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCameras = QtWidgets.QMenu(self.menubar)
        self.menuCameras.setObjectName("menuCameras")
        self.menuRecordings = QtWidgets.QMenu(self.menubar)
        self.menuRecordings.setObjectName("menuRecordings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_New_Camera = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Camera.setObjectName("actionAdd_New_Camera")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_New = QtWidgets.QAction(MainWindow)
        self.actionAdd_New.setObjectName("actionAdd_New")
        self.actionAdd_Webcam = QtWidgets.QAction(MainWindow)
        self.actionAdd_Webcam.setObjectName("actionAdd_Webcam")
        self.actionView_Recordings = QtWidgets.QAction(MainWindow)
        self.actionView_Recordings.setObjectName("actionView_Recordings")
        self.menuFile.addAction(self.actionExit)
        self.menuCameras.addAction(self.actionAdd_New)
        self.menuCameras.addAction(self.actionAdd_Webcam)
        self.menuRecordings.addAction(self.actionView_Recordings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCameras.menuAction())
        self.menubar.addAction(self.menuRecordings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watchdog - Control Panel"))
        self.WatchdogLogo.setText(_translate("MainWindow", "Watchdog Home Control Panel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCameras.setTitle(_translate("MainWindow", "Cameras"))
        self.menuRecordings.setTitle(_translate("MainWindow", "Recordings"))
        self.actionAdd_New_Camera.setText(_translate("MainWindow", "Add New Camera"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_New.setText(_translate("MainWindow", "Add New"))
        self.actionAdd_Webcam.setText(_translate("MainWindow", "Add Webcam"))
        self.actionView_Recordings.setText(_translate("MainWindow", "View Recordings"))
