# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_control_panel/app/frontend/gui/RecordingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordingsView(object):
    def setupUi(self, RecordingsView):
        RecordingsView.setObjectName("RecordingsView")
        RecordingsView.setWindowModality(QtCore.Qt.ApplicationModal)
        RecordingsView.resize(579, 417)
        RecordingsView.setMinimumSize(QtCore.QSize(579, 367))
        RecordingsView.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(RecordingsView)
        self.gridLayout.setObjectName("gridLayout")
        self.refreshList = QtWidgets.QPushButton(RecordingsView)
        self.refreshList.setObjectName("refreshList")
        self.gridLayout.addWidget(self.refreshList, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RecordingsView)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.treeWidget = QtWidgets.QTreeWidget(RecordingsView)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(RecordingsView)
        self.groupBox.setMaximumSize(QtCore.QSize(171, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.fromInput = QtWidgets.QDateTimeEdit(self.groupBox)
        self.fromInput.setObjectName("fromInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fromInput)
        self.toInput = QtWidgets.QDateTimeEdit(self.groupBox)
        self.toInput.setObjectName("toInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.toInput)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.applyFilters = QtWidgets.QPushButton(self.groupBox)
        self.applyFilters.setObjectName("applyFilters")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.applyFilters)
        self.clearFilters = QtWidgets.QPushButton(self.groupBox)
        self.clearFilters.setObjectName("clearFilters")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.clearFilters)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exit = QtWidgets.QPushButton(RecordingsView)
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)

        self.retranslateUi(RecordingsView)
        QtCore.QMetaObject.connectSlotsByName(RecordingsView)

    def retranslateUi(self, RecordingsView):
        _translate = QtCore.QCoreApplication.translate
        RecordingsView.setWindowTitle(_translate("RecordingsView", "Recordings"))
        self.refreshList.setText(_translate("RecordingsView", "Refresh List"))
        self.label.setText(_translate("RecordingsView", "Recordings"))
        self.treeWidget.headerItem().setText(0, _translate("RecordingsView", "Videos"))
        self.groupBox.setTitle(_translate("RecordingsView", "Filters"))
        self.label_2.setText(_translate("RecordingsView", "From"))
        self.label_3.setText(_translate("RecordingsView", "To"))
        self.applyFilters.setText(_translate("RecordingsView", "Apply Filters"))
        self.clearFilters.setText(_translate("RecordingsView", "Clear All Filters"))
        self.exit.setText(_translate("RecordingsView", "Exit"))
