# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_control_panel/app/frontend/gui/StreamView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QWidget


class Ui_StreamView(QWidget):
    def setupUi(self, StreamView):
        StreamView.setObjectName("StreamView")
        StreamView.resize(243, 262)
        StreamView.setMinimumSize(QtCore.QSize(243, 262))
        self.gridLayout = QtWidgets.QGridLayout(StreamView)
        self.gridLayout.setObjectName("gridLayout")
        self.stream_view = QtWidgets.QLabel(StreamView)
        self.stream_view.setMinimumSize(QtCore.QSize(150, 150))
        self.stream_view.setObjectName("stream_view")
        self.gridLayout.addWidget(self.stream_view, 0, 0, 1, 1)
        self.cameraName = QtWidgets.QLabel(StreamView)
        self.cameraName.setObjectName("cameraName")
        self.gridLayout.addWidget(self.cameraName, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.removeStream = QtWidgets.QPushButton(StreamView)
        self.removeStream.setObjectName("removeStream")
        self.horizontalLayout.addWidget(self.removeStream)
        self.pauseStream = QtWidgets.QPushButton(StreamView)
        self.pauseStream.setObjectName("pauseStream")
        self.horizontalLayout.addWidget(self.pauseStream)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.location = QtWidgets.QLabel(StreamView)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 2, 0, 1, 1)

        self.retranslateUi(StreamView)
        QtCore.QMetaObject.connectSlotsByName(StreamView)

    def retranslateUi(self, StreamView):
        _translate = QtCore.QCoreApplication.translate
        # StreamView.setWindowTitle(_translate("StreamView", "Form"))
        self.stream_view.setText(_translate("StreamView", "No Stream"))
        self.cameraName.setText(_translate("StreamView", "Unknown Camera"))
        self.removeStream.setText(_translate("StreamView", "Remove"))
        self.pauseStream.setText(_translate("StreamView", "Pause Stream"))
        self.location.setText(_translate("StreamView", "Unknown Location"))

    def update_frame(self, frame):
        height, width, bpc = frame.shape
        bpl = bpc * width
        self.stream_view.setPixmap(QPixmap.fromImage(QImage(frame.data, width, height, bpl, QImage.Format_RGB888)))
        self.update()
