# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_control_panel/app/frontend/gui/StreamView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QWidget


class Ui_StreamView(QWidget):
    def setupUi(self, StreamView):
        StreamView.setObjectName("StreamView")
        StreamView.resize(489, 479)
        StreamView.setMinimumSize(QtCore.QSize(243, 262))
        self.gridLayout = QtWidgets.QGridLayout(StreamView)
        self.gridLayout.setObjectName("gridLayout")
        self.stream_view = QtWidgets.QLabel(StreamView)
        self.stream_view.setMinimumSize(QtCore.QSize(150, 150))
        self.stream_view.setObjectName("stream_view")
        # self.stream_view.setScaledContents(True)
        self.gridLayout.addWidget(self.stream_view, 0, 0, 1, 1)
        self.cameraName = QtWidgets.QLabel(StreamView)
        self.cameraName.setMaximumSize(QtCore.QSize(16777215, 27))
        self.cameraName.setObjectName("cameraName")
        self.gridLayout.addWidget(self.cameraName, 1, 0, 1, 1)
        self.location = QtWidgets.QLabel(StreamView)
        self.location.setMaximumSize(QtCore.QSize(16777215, 27))
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(StreamView)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.detectedLabel = QtWidgets.QLabel(self.groupBox)
        self.detectedLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        self.detectedLabel.setObjectName("detectedLabel")
        self.gridLayout_2.addWidget(self.detectedLabel, 0, 1, 1, 1)
        self.removeStream = QtWidgets.QPushButton(self.groupBox)
        self.removeStream.setObjectName("removeStream")
        self.gridLayout_2.addWidget(self.removeStream, 2, 1, 1, 1)
        self.pauseStream = QtWidgets.QPushButton(self.groupBox)
        self.pauseStream.setObjectName("pauseStream")
        self.gridLayout_2.addWidget(self.pauseStream, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 1)

        self.retranslateUi(StreamView)
        QtCore.QMetaObject.connectSlotsByName(StreamView)

    def retranslateUi(self, StreamView):
        _translate = QtCore.QCoreApplication.translate
        # StreamView.setWindowTitle(_translate("StreamView", "Form"))
        self.stream_view.setText(_translate("StreamView", "Camera Stream Unavailable"))
        self.cameraName.setText(_translate("StreamView", "Unknown Camera"))
        self.location.setText(_translate("StreamView", "Unknown Location"))
        self.detectedLabel.setText(_translate("StreamView", "º"))
        self.removeStream.setText(_translate("StreamView", "Remove"))
        self.pauseStream.setText(_translate("StreamView", "Pause Stream"))
        self.location.setText(_translate("StreamView", "Unknown Location"))

    def update_frame(self, frame):
        if frame is not None:
            height, width, bpc = frame.shape
            bpl = bpc * width
            self.stream_view.setPixmap(QPixmap.fromImage(QImage(frame.data, width, height, bpl, QImage.Format_RGB888)))
            self.update()
